name: Create release

on:
  push:
    branches: [ "release" ]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    name: Release with PR title as tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR title and extract tag
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed",
              sort: "updated",
              direction: "desc",
              per_page: 5
            });

            const pr = prs.data.find(pr => pr.merge_commit_sha === context.sha);
            if (!pr) {
              core.setFailed("No matching PR found for this commit.");
            } else {
              // Extract tag from PR title (assumes tag is like 0.0.1)
              const pr_title = pr.title;
              const tag = pr_title.match(/\d+\.\d+\.\d+/);
              if (!tag) {
                core.setFailed("No valid tag found in the PR title.");
              } else {
                core.setOutput("tag", tag[0]);  // Set extracted tag as output
                core.setOutput("body", pr.body || "No PR body provided.");
              }
            }

      - name: Create artifacts
        run: touch ./dummy.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ./dummy.txt
          name: dummy.txt

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_pr.outputs.tag }}   # Use tag from PR title
          name: ${{ steps.get_pr.outputs.tag }}  # Use tag as release title
          body: ${{ steps.get_pr.outputs.body }} # Use PR body as release description
          artifacts: ./dummy.txt
