name: Create release

on:
  push:
    branches: [ "release" ]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    name: Release on push to release branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR body
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed",
              sort: "updated",
              direction: "desc",
              per_page: 1,
            });

            const pr = prs.data.find(pr => pr.merge_commit_sha === context.sha);
            if (!pr) {
              core.setFailed("No matching PR found for this commit.");
            } else {
              core.setOutput("body", pr.body || "No PR body provided.");
            }

      - name: Create artifacts
        run: touch ./dummy.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ./dummy.txt
          name: dummy.txt

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: 0.0.1
          name: Test Release
          body: ${{ steps.get_pr.outputs.body }}
          artifacts: ./dummy.txt
